version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  virtual-threads-app:
    container_name: virtual-threads
    depends_on:
      - postgres
    build:
      context: ../api.distritos.virtual.threads
    ports:
      - 8080:8080
