version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  client-test:
    container_name: client-test
    build:
      context: ../api.testes
    environment:
      PORT: 3000
      SERVER_URL: http://virtual-threads-app:8080
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/benchmarks:/app/benchmark


  virtual-threads-app:
    container_name: virtual-threads
    depends_on:
      - postgres
    build:
      context: ../api.distritos.virtual.threads
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4g
          # pids: 50
        reservations:
          memory: 2g
    environment:
      VIRTUAL_THREAD: 'true'
      JDBC_CONNECTION: jdbc:postgresql://postgres:5432/postgres
    ports:
      - 8080:8080
